package net.lovelace.vesuvio.check.statistical;

import net.lovelace.vesuvio.check.CheckResult;
import net.lovelace.vesuvio.data.UserData;

import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

/**
 * Mathematical Mouse Sensitivity & GCD (Greatest Common Divisor) Aim Analyzer.
 * Inspired by GrimAC and Polar.
 *
 * In vanilla Minecraft, rotation deltas are generated by integer mouse counts multiplied by:
 * constant = (sensitivity * 0.6 + 0.2)^3 * 1.2
 *
 * Algorithmic Aimbots, Killaura, and Silent Aim calculate angles via trigonometry
 * atan2(dz, dx), producing smooth floating-point deltas that fail GCD quantization.
 *
 * False-Positive-Free Design:
 * 1. Only checks during active combat (within 4s of combat actions).
 * 2. Requires both yaw and pitch to move within realistic tracking speeds (1.5° to 30°).
 * 3. Requires a consecutive failure streak (>= 5) before flagging to prevent single-packet jitter.
 * 4. Normalizes yaw wrapping and excludes teleports.
 *
 * Author: Lovelace
 */
public final class GCDAimCheck {

    private static final float MIN_ROTATION = 1.5f;  // Minimum rotation on both axes to analyze cross-axis GCD
    private static final float MAX_ROTATION = 30.0f; // Exclude flick/teleport/180 turns
    private static final int STREAK_THRESHOLD = 5;   // Must fail 5 consecutive times during combat

    public CheckResult check(UserData data, float deltaYaw, float deltaPitch) {
        // 1. Only analyze aimbot rotations during combat interactions (not while walking/jumping around)
        if (!data.isInCombat()) {
            data.decrementGcdStreak();
            return CheckResult.pass("GCDAim");
        }

        // 2. Both yaw and pitch must have moved significantly but within normal tracking speeds
        if (deltaYaw < MIN_ROTATION || deltaPitch < MIN_ROTATION
                || deltaYaw > MAX_ROTATION || deltaPitch > MAX_ROTATION) {
            return CheckResult.pass("GCDAim");
        }

        // 3. Euclidean GCD on rotation deltas
        double gcd = calculateGCD(deltaYaw, deltaPitch);

        // In Minecraft, even at 0% sensitivity, the smallest divisor is 0.0096 degrees.
        // Aimbots using software trigonometry collapse GCD below 0.008 degrees.
        if (gcd < 0.008) {
            data.incrementGcdStreak();

            if (data.getGcdSuspiciousStreak() >= STREAK_THRESHOLD) {
                Map<String, Object> details = new HashMap<>();
                details.put("deltaYaw", deltaYaw);
                details.put("deltaPitch", deltaPitch);
                details.put("calculatedGCD", gcd);
                details.put("streak", data.getGcdSuspiciousStreak());

                String explanation = String.format(Locale.US,
                        "Invalid mouse quantization streak: %d (ΔYaw: %.2f°, ΔPitch: %.2f°, GCD: %.6f)",
                        data.getGcdSuspiciousStreak(), deltaYaw, deltaPitch, gcd);

                // Reset streak so we don't spam 20 alerts per second
                data.resetGcdStreak();

                return CheckResult.flag("GCDAim", 0.94, 2.0, explanation, details);
            }
        } else {
            // Legitimately quantized mouse rotation steps decay the streak
            data.decrementGcdStreak();
        }

        return CheckResult.pass("GCDAim");
    }

    public static double calculateGCD(double a, double b) {
        if (a < b) {
            double temp = a;
            a = b;
            b = temp;
        }
        if (b < 0.001) {
            return b;
        }
        int iterations = 0;
        while (b > 0.001 && iterations++ < 50) {
            double quotient = Math.floor((a / b) + 1e-5);
            double r = a - (quotient * b);
            if (r < 0) {
                r = 0;
            }

            // If remainder is negligible (< 0.0005 degrees), b is an exact divisor
            if (r < 0.0005 || (b - r) < 0.0005) {
                return b;
            }
            a = b;
            b = r;
        }
        return b;
    }
}
